const LOAN_MIN_AMOUNT = 5e4, LOAN_MAX_AMOUNT = 75e5, FROM_LOAN_AMOUNT = 5e4, STEP_IN_LOAN_AMOUNT = 1e3,
    LOAN_MIN_AMOUNT_IN_LAKH = 3, LOAN_MAX_AMOUNT_IN_LAKH = 1e3, FROM_LOAN_AMOUNT_IN_LAKH = 300,
    STEP_IN_LOAN_AMOUNT_IN_LAKH = 1, LOAN_TENTURE_MONTH_MIN_VALUE = 0, LOAN_TENTURE_MONTH_MAX_VALUE = 120,
    LOAN_TENTURE_MONTH_FROM_MIN_VALUE = 1, LOAN_TENTURE_MONTH_START_VALUE = 1, LOAN_TENTURE_YEAR_MIN_VALUE = 0,
    LOAN_TENTURE_YEAR_MAX_VALUE = 10, LOAN_TENTURE_YEAR_FROM_MIN_VALUE = .5, LOAN_TENTURE_YEAR_START_VALUE = .5,
    LOAN_INTEREST_RATE_MIN_VALUE = 12, LOAN_INTEREST_RATE_START_VALUE = 20, LOAN_INTEREST_RATE_MAX_VALUE = 45;